FROM ubuntu

WORKDIR /app

COPY requirements.txt /app
COPY todo_project /app/todo_project

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    python3 -m venv /app/venv && \
    . /app/venv/bin/activate && \
    pip install -r requirements.txt && \
    ls -l /app/todo_project

WORKDIR /app/todo_project

ENTRYPOINT ["/app/venv/bin/python"]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]